# Generated by Django 5.2.16 on 2026-08-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0002_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_vcount',
            field=models.IntegerField(default=1),
        ),
    ]
