# Generated by Django 5.2.16 on 2026-08-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0005_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='student_address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='student_email',
        ),
    ]
